### ISSUE TITLE
Boje, paleta boja

### ISSUE THREAD

**Issue by Ivan-Jank0vic** [AntonioToni/4mat#2]
Treba promjenit sve 
`color: salmon` 
itd u rgb, da je lakse neku paletu boja napravit po kojoj ce cijela stranica bit.

Malo pogledaj po nekom [palette generatoru](https://colordesigner.io/) i nađi boje koje ti se sviđaju.

**Comment by AntonioToni** [comment]
Sve `color: salmon` pribaceno u rgb
